# Generated by Django 2.2.1 on 2019-06-08 13:31
from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('is_slot_available', models.CharField(default=0, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(default=0, max_length=10)),
                ('customer_name', models.CharField(default='', max_length=150)),
                ('contact_no', models.CharField(default='', max_length=10)),
                ('in_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('out_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('slot_number', models.CharField(default=0, max_length=2)),
                ('is_checked_out', models.CharField(default=0, max_length=2)),
            ],
        ),

    ]
